### ISSUE TITLE
Role-based user workflows

### ISSUE THREAD

**Issue by ygoex** [National-Forestry-Authority/farmers#123]
Finalisation of straight-forward user workflows based on the user role – such that such that power users can be notified of changes proposed to all data held on the system and then approve / comment / reject these changes, based upon an agreed rule and procedure set.

**Comment by ygoex** [comment]
Related issues:

- [ ] https://github.com/National-Forestry-Authority/farmers/issues/105

**Comment by ygoex** [comment]
@Rashids2021 will provide a user workflow.

**Comment by peacog** [comment]
Closed as duplicate of https://github.com/National-Forestry-Authority/farmers/issues/165
