### ISSUE TITLE
Bug related to updated theme?

### ISSUE THREAD

**Issue by LeScruf** [National-Forestry-Authority/farmers#169]
Following the update of the system recently, it seems some functions are no longer activated. For example:

1. Power Users (in this case the data entrants) - can not logout or see their profile name on the upper extreme right of the page and can not edit the tree farmer details
2. Administrators (Me) I can not edit farmer details.

Please help and correct these bags, to restore the functionality of the system.

**Comment by LeScruf** [comment]
Fixed by @peacog

**Comment by peacog** [comment]
Hi @LeScruf @Rashids2021 

The bugs have been fixed. I've given all users permission to see the toolbar. 

The Edit farmer button had been accidentally hidden. It's now back where it was before, at the top of the Farmer details tab.
![image](https://github.com/National-Forestry-Authority/farmers/assets/1312689/5c84947d-60fe-44bc-b7db-472bb2b03a10)
