### ISSUE TITLE
"Add offer/licence" overlay form dependent filtering

### ISSUE THREAD

**Issue by pcambra** [National-Forestry-Authority/farmers#8]
When accessing http://dev-hsk.nfa-fmis.net/tree-farmer-overview/licences?title=Test%20farmer and clicking on "Add offer/licence", there's a form poping up.
When selecting a  Central Forest Reserve (CFR), the blocks available in the "Block ID" dropdown should exist in said CFR.

**Comment by peacog** [comment]
Depends on #9

**Comment by peacog** [comment]
Done
